services:
  turath-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turath_laravel_api
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - turath-network

networks:
  turath-network:
    driver: bridge