services:
  turath-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turath_laravel_api
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8000:8000"
    environment:
      QUEUE_CONNECTION: background
      OPEN_LIBRARY_QUEUE_CONNECTION: background
    volumes:
      - .:/var/www/html
      - turath-api-vendor:/var/www/html/vendor
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    networks:
      - turath-network

networks:
  turath-network:
    driver: bridge

volumes:
  turath-api-vendor:
